### ISSUE TITLE
More bald?

### ISSUE THREAD

**Issue by alwavshumilin** [DougDougGithub/Babagaboosh#4] opened 2024-01-12 22:01 UTC
I mean, the author is already bald, but I feel like it’s not enough. Please fix, THX <3

**Comment by wolfmic** [comment] 2024-01-12 22:06
probably a duplicate of #1

**Comment by alwavshumilin** [comment] 2024-01-12 22:09
Yeah, but dropping static refs is not enough either. We might experience pointers overload, hence something must be done on the low level

**Comment by MrManiacc** [comment] 2024-01-12 22:09
@DougDougGithub this is a duplicate of #1 can we close this issue?

**Closed as completed** 2024-01-13 22:39 UTC
